### PR TITLE
Put my two cents in General Remarks and Time management sections

### PR DESCRIPTION
**Pull request by paullo0106**
as title

### CODE REVIEW

**Comment by paullo0106** [comment]
@zero323 Please feel free to comment and accept the pull request if appropriate, thanks.

**Comment by zero323** [comment]
@paullo0106 Sorry, I missed that. I'll finish my coffee and take a look.

**Comment by zero323** [comment]
So, I am entirely convinced that putting detail about course organization is a good idea. This is not only the part which most likely change in the future, but can raise some concerns about revealing to much as well. 
I am not sure about relevance of the line 115 in context of the Internet connections.

Here is my idea:
- drop line 69
- move 115 to the General Remarks

I would probably rewrite "personal" parts like IMHO. Not that I am language purist but it is a collaborative work so without going through logs it is not clear whose opinion it is.

**Comment by paullo0106** [comment]
Yeah, I agree with your point. I made some changes:
- Drop line 69 which includes some schedule details.
- Don't use IMHO personal comment.
- line 115 is already in General Remarks section

**Comment by paullo0106** [comment]
@zero323, Ya, I agree with your point. I thus made some changes:
- Drop line 69 which includes some schedule details.
- Don't use IMHO personal comment.
- line 115 is already in General Remarks section

**Comment by zero323** [comment]
Thanks.

**Pull request merged**
